## 🤖 CodeAlpha AI Internship - Task 2
## AI-Powered Healthcare FAQ Chatbot

## 📖 Project Description

This project implements an AI-powered Healthcare FAQ Chatbot that answers user questions by retrieving the most relevant response from a curated FAQ knowledge base. The chatbot uses Natural Language Processing (NLP), TF-IDF vectorization, and Cosine Similarity to match user queries with stored healthcare FAQs from the MedQuAD and Mental Health FAQ datasets. 

### Workflow
### Step 1: Install Required Packages
### Step 2: Import Libraries
### Step 3: Load and Merge Datasets
### Step 4: Preprocess and Vectorize Text
### Step 5: Preprocess User Query
### Step 6: Compute TF-IDF & Cosine Similarity
### Step 7: Generate Best Matching Response
### Step 8: Build and Launch Streamlit/Gradio Chatbot

# Step 1 Install Required Package

In [2]:
!pip install -r requirements.txt

Collecting pandas==2.3.1 (from -r requirements.txt (line 1))
  Downloading pandas-2.3.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy==2.3.2 (from -r requirements.txt (line 2))
  Downloading numpy-2.3.2-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting scikit-learn==1.7.1 (from -r requirements.txt (line 3))
  Downloading scikit_learn-1.7.1-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting nltk==3.9.1 (from -r requirements.txt (line 4))
  Downloading nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting streamlit==1.48.0 (from -r requirements.txt (line 5))
  Downloading streamlit-1.48.0-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from pandas==2.3.1->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from pandas==2.3.1->-r requirements.txt (line 1)) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from pandas==2.3.1->-r requirements.txt (line 1)) (2026.2)
Collecting scipy>=1.8.0 (from scikit-learn==1.7.1->-r requirements.txt (line 3))
  Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn==1.7.1->-r requirements.txt (line 3))
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn==1.7.1->-r requirements.txt (line 3))
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: click in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from nltk==3.9.1->-r requirements.txt (line 4)) (8.3.0)
Collecting regex>=2021.8.3 (from nltk==3.9.1->-r requirements.txt (line 4))
  Downloading regex-2026.5.9-cp312-cp312-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: tqdm in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from nltk==3.9.1->-r requirements.txt (line 4)) (4.68.2)
Collecting altair!=5.4.0,!=5.4.1,<6,>=4.0 (from streamlit==1.48.0->-r requirements.txt (line 5))
  Downloading altair-5.5.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: blinker<2,>=1.5.0 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from streamlit==1.48.0->-r requirements.txt (line 5)) (1.9.0)
Collecting cachetools<7,>=4.0 (from streamlit==1.48.0->-r requirements.txt (line 5))
  Using cached cachetools-6.2.6-py3-none-any.whl.metadata (5.6 kB)
Collecting packaging<26,>=20 (from streamlit==1.48.0->-r requirements.txt (line 5))
  Using cached packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pillow<12,>=7.1.0 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from streamlit==1.48.0->-r requirements.txt (line 5)) (11.3.0)
Collecting protobuf<7,>=3.20 (from streamlit==1.48.0->-r requirements.txt (line 5))
  Downloading protobuf-6.33.6-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting pyarrow>=7.0 (from streamlit==1.48.0->-r requirements.txt (line 5))
  Downloading pyarrow-24.0.0-cp312-cp312-win_amd64.whl.metadata (3.0 kB)
Requirement already satisfied: requests<3,>=2.27 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from streamlit==1.48.0->-r requirements.txt (line 5)) (2.34.2)
Collecting tenacity<10,>=8.1.0 (from streamlit==1.48.0->-r requirements.txt (line 5))
  Using cached tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: toml<2,>=0.10.1 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from streamlit==1.48.0->-r requirements.txt (line 5)) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from streamlit==1.48.0->-r requirements.txt (line 5)) (4.15.0)
Collecting watchdog<7,>=2.1.5 (from streamlit==1.48.0->-r requirements.txt (line 5))
  Using cached watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit==1.48.0->-r requirements.txt (line 5))
  Downloading gitpython-3.1.50-py3-none-any.whl.metadata (14 kB)
Collecting pydeck<1,>=0.8.0b4 (from streamlit==1.48.0->-r requirements.txt (line 5))
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from streamlit==1.48.0->-r requirements.txt (line 5)) (6.5.7)
Requirement already satisfied: jinja2 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit==1.48.0->-r requirements.txt (line 5)) (3.1.6)
Collecting jsonschema>=3.0 (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit==1.48.0->-r requirements.txt (line 5))
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting narwhals>=1.14.2 (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit==1.48.0->-r requirements.txt (line 5))
  Using cached narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: colorama in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from click->nltk==3.9.1->-r requirements.txt (line 4)) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit==1.48.0->-r requirements.txt (line 5))
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit==1.48.0->-r requirements.txt (line 5))
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from requests<3,>=2.27->streamlit==1.48.0->-r requirements.txt (line 5)) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from requests<3,>=2.27->streamlit==1.48.0->-r requirements.txt (line 5)) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from requests<3,>=2.27->streamlit==1.48.0->-r requirements.txt (line 5)) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from requests<3,>=2.27->streamlit==1.48.0->-r requirements.txt (line 5)) (2026.5.20)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit==1.48.0->-r requirements.txt (line 5)) (3.0.3)
Collecting attrs>=22.2.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit==1.48.0->-r requirements.txt (line 5))
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit==1.48.0->-r requirements.txt (line 5))
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit==1.48.0->-r requirements.txt (line 5))
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit==1.48.0->-r requirements.txt (line 5))
  Downloading rpds_py-2026.5.1-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: six>=1.5 in C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages (from python-dateutil>=2.8.2->pandas==2.3.1->-r requirements.txt (line 1)) (1.17.0)
Downloading pandas-2.3.1-cp312-cp312-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/11.0 MB 6.7 MB/s eta 0:00:02
   ---------- ----------------------------- 2.9/11.0 MB 7.3 MB/s eta 0:00:02
   ------------------- -------------------- 5.2/11.0 MB 8.6 MB/s eta 0:00:01
   ----------------------- ---------------- 6.6/11.0 MB 7.9 MB/s eta 0:00:01
   -------------------------- ------------- 7.3/11.0 MB 7.0 MB/s eta 0:00:01
   ----------------------------- ---------- 8.1/11.0 MB 6.4 MB/s eta 0:00:01
   ------------------------------ --------- 8.4/11.0 MB 6.0 MB/s eta 0:00:01
   -------------------------------- ------- 8.9/11.0 MB 5.4 MB/s eta 0:00:01
   ---------------------------------- ----- 9.4/11.0 MB 5.1 MB/s eta 0:00:01
   ------------------------------------ --- 10.0/11.0 MB 4.8 MB/s eta 0:00:01
   -------------------------------------- - 10.5/11.0 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 4.2 MB/s  0:00:02
Downloading numpy-2.3.2-cp312-cp312-win_amd64.whl (12.8 MB)
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 2.8 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/12.8 MB 2.7 MB/s eta 0:00:05
   ---- ----------------------------------- 1.6/12.8 MB 2.8 MB/s eta 0:00:05
   ------- -------------------------------- 2.4/12.8 MB 2.9 MB/s eta 0:00:04
   --------- ------------------------------ 2.9/12.8 MB 2.8 MB/s eta 0:00:04
   ----------- ---------------------------- 3.7/12.8 MB 2.9 MB/s eta 0:00:04
   ------------- -------------------------- 4.2/12.8 MB 2.9 MB/s eta 0:00:03
   --------------- ------------------------ 5.0/12.8 MB 3.0 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.8 MB 3.0 MB/s eta 0:00:03
   -------------------- ------------------- 6.6/12.8 MB 3.1 MB/s eta 0:00:03
   ---------------------- ----------------- 7.3/12.8 MB 3.1 MB/s eta 0:00:02
   ------------------------- -------------- 8.1/12.8 MB 3.2 MB/s eta 0:00:02
   --------------------------- ------------ 8.9/12.8 MB 3.2 MB/s eta 0:00:02
   ------------------------------ --------- 9.7/12.8 MB 3.2 MB/s eta 0:00:01
   -------------------------------- ------- 10.5/12.8 MB 3.3 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.8 MB 3.3 MB/s eta 0:00:01
   -------------------------------------- - 12.3/12.8 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 3.3 MB/s  0:00:03
Downloading scikit_learn-1.7.1-cp312-cp312-win_amd64.whl (8.7 MB)
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.7 MB 4.2 MB/s eta 0:00:02
   ------ --------------------------------- 1.3/8.7 MB 2.7 MB/s eta 0:00:03
   ---------- ----------------------------- 2.4/8.7 MB 3.4 MB/s eta 0:00:02
   -------------- ------------------------- 3.1/8.7 MB 3.6 MB/s eta 0:00:02
   ------------------- -------------------- 4.2/8.7 MB 3.8 MB/s eta 0:00:02
   ------------------------ --------------- 5.2/8.7 MB 3.9 MB/s eta 0:00:01
   -------------------------- ------------- 5.8/8.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------- ----------- 6.3/8.7 MB 3.7 MB/s eta 0:00:01
   ---------------------------- ----------- 6.3/8.7 MB 3.7 MB/s eta 0:00:01
   --------------------------------- ------ 7.3/8.7 MB 3.3 MB/s eta 0:00:01
   -------------------------------------- - 8.4/8.7 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 8.7/8.7 MB 3.2 MB/s  0:00:02
Downloading nltk-3.9.1-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   --------------------------- ------------ 1.0/1.5 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 4.7 MB/s  0:00:00
Downloading streamlit-1.48.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.9 MB 5.6 MB/s eta 0:00:02
   ------ --------------------------------- 1.6/9.9 MB 3.4 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.9 MB 3.8 MB/s eta 0:00:03
   ------------ --------------------------- 3.1/9.9 MB 3.5 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/9.9 MB 3.5 MB/s eta 0:00:02
   -------------- ------------------------- 3.7/9.9 MB 2.7 MB/s eta 0:00:03
   ---------------- ----------------------- 4.2/9.9 MB 2.8 MB/s eta 0:00:03
   --------------------- ------------------ 5.2/9.9 MB 3.0 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.9 MB 3.1 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.9 MB 3.1 MB/s eta 0:00:02
   ----------------------------- ---------- 7.3/9.9 MB 3.2 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.9 MB 2.8 MB/s eta 0:00:01
   --------------------------------- ------ 8.4/9.9 MB 2.9 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 2.9 MB/s  0:00:03
Downloading altair-5.5.0-py3-none-any.whl (731 kB)
   ---------------------------------------- 0.0/731.2 kB ? eta -:--:--
   ---------------------------------------- 731.2/731.2 kB 4.3 MB/s  0:00:00
Using cached cachetools-6.2.6-py3-none-any.whl (11 kB)
Downloading gitpython-3.1.50-py3-none-any.whl (212 kB)
Using cached gitdb-4.0.12-py3-none-any.whl (62 kB)
Using cached packaging-25.0-py3-none-any.whl (66 kB)
Downloading protobuf-6.33.6-cp310-abi3-win_amd64.whl (437 kB)
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/11.3 MB 6.1 MB/s eta 0:00:02
   --------- ------------------------------ 2.6/11.3 MB 6.3 MB/s eta 0:00:02
   -------------- ------------------------- 4.2/11.3 MB 6.1 MB/s eta 0:00:02
   ------------------- -------------------- 5.5/11.3 MB 6.1 MB/s eta 0:00:01
   ------------------------ --------------- 6.8/11.3 MB 6.2 MB/s eta 0:00:01
   ---------------------------- ----------- 8.1/11.3 MB 6.2 MB/s eta 0:00:01
   ------------------------------- -------- 8.9/11.3 MB 5.8 MB/s eta 0:00:01
   ---------------------------------- ----- 9.7/11.3 MB 5.5 MB/s eta 0:00:01
   ------------------------------------ --- 10.2/11.3 MB 5.1 MB/s eta 0:00:01
   -------------------------------------- - 10.7/11.3 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 4.6 MB/s  0:00:02
Downloading smmap-5.0.3-py3-none-any.whl (24 kB)
Using cached tenacity-9.1.4-py3-none-any.whl (28 kB)
Using cached watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached jsonschema-4.26.0-py3-none-any.whl (90 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Using cached narwhals-2.22.1-py3-none-any.whl (454 kB)
Downloading pyarrow-24.0.0-cp312-cp312-win_amd64.whl (27.4 MB)
   ---------------------------------------- 0.0/27.4 MB ? eta -:--:--
    --------------------------------------- 0.5/27.4 MB 2.8 MB/s eta 0:00:10
   - -------------------------------------- 1.0/27.4 MB 2.6 MB/s eta 0:00:10
   -- ------------------------------------- 1.6/27.4 MB 2.7 MB/s eta 0:00:10
   --- ------------------------------------ 2.4/27.4 MB 2.8 MB/s eta 0:00:09
   ---- ----------------------------------- 2.9/27.4 MB 2.8 MB/s eta 0:00:09
   ----- ---------------------------------- 3.7/27.4 MB 2.8 MB/s eta 0:00:09
   ------ --------------------------------- 4.2/27.4 MB 2.9 MB/s eta 0:00:09
   ------- -------------------------------- 5.0/27.4 MB 2.9 MB/s eta 0:00:08
   -------- ------------------------------- 5.8/27.4 MB 3.0 MB/s eta 0:00:08
   --------- ------------------------------ 6.3/27.4 MB 3.0 MB/s eta 0:00:07
   ---------- ----------------------------- 7.1/27.4 MB 3.1 MB/s eta 0:00:07
   ----------- ---------------------------- 7.9/27.4 MB 3.1 MB/s eta 0:00:07
   ------------ --------------------------- 8.7/27.4 MB 3.2 MB/s eta 0:00:06
   ------------- -------------------------- 9.4/27.4 MB 3.2 MB/s eta 0:00:06
   -------------- ------------------------- 10.2/27.4 MB 3.3 MB/s eta 0:00:06
   ---------------- ----------------------- 11.3/27.4 MB 3.3 MB/s eta 0:00:05
   ----------------- ---------------------- 12.1/27.4 MB 3.3 MB/s eta 0:00:05
   ------------------ --------------------- 12.8/27.4 MB 3.4 MB/s eta 0:00:05
   -------------------- ------------------- 13.9/27.4 MB 3.4 MB/s eta 0:00:04
   --------------------- ------------------ 14.9/27.4 MB 3.5 MB/s eta 0:00:04
   ---------------------- ----------------- 15.7/27.4 MB 3.5 MB/s eta 0:00:04
   ------------------------ --------------- 16.8/27.4 MB 3.6 MB/s eta 0:00:03
   -------------------------- ------------- 17.8/27.4 MB 3.6 MB/s eta 0:00:03
   --------------------------- ------------ 18.9/27.4 MB 3.7 MB/s eta 0:00:03
   ----------------------------- ---------- 19.9/27.4 MB 3.7 MB/s eta 0:00:03
   ------------------------------ --------- 21.0/27.4 MB 3.8 MB/s eta 0:00:02
   -------------------------------- ------- 22.3/27.4 MB 3.8 MB/s eta 0:00:02
   ---------------------------------- ----- 23.3/27.4 MB 3.9 MB/s eta 0:00:02
   ----------------------------------- ---- 24.4/27.4 MB 3.9 MB/s eta 0:00:01
   ------------------------------------- -- 25.4/27.4 MB 3.9 MB/s eta 0:00:01
   -------------------------------------- - 26.2/27.4 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  26.7/27.4 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.4 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 27.4/27.4 MB 3.7 MB/s  0:00:07
Using cached referencing-0.37.0-py3-none-any.whl (26 kB)
Downloading regex-2026.5.9-cp312-cp312-win_amd64.whl (277 kB)
Downloading rpds_py-2026.5.1-cp312-cp312-win_amd64.whl (229 kB)
Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
    --------------------------------------- 0.5/36.5 MB 3.4 MB/s eta 0:00:11
   - -------------------------------------- 1.3/36.5 MB 3.0 MB/s eta 0:00:12
   -- ------------------------------------- 1.8/36.5 MB 2.9 MB/s eta 0:00:13
   -- ------------------------------------- 2.6/36.5 MB 3.0 MB/s eta 0:00:12
   --- ------------------------------------ 3.1/36.5 MB 3.0 MB/s eta 0:00:12
   ---- ----------------------------------- 3.9/36.5 MB 3.1 MB/s eta 0:00:11
   ----- ---------------------------------- 4.7/36.5 MB 3.2 MB/s eta 0:00:11
   ------ --------------------------------- 5.5/36.5 MB 3.2 MB/s eta 0:00:10
   ------ --------------------------------- 6.3/36.5 MB 3.2 MB/s eta 0:00:10
   ------- -------------------------------- 7.1/36.5 MB 3.3 MB/s eta 0:00:09
   -------- ------------------------------- 7.9/36.5 MB 3.3 MB/s eta 0:00:09
   --------- ------------------------------ 8.7/36.5 MB 3.4 MB/s eta 0:00:09
   ---------- ----------------------------- 9.7/36.5 MB 3.4 MB/s eta 0:00:08
   ----------- ---------------------------- 10.5/36.5 MB 3.5 MB/s eta 0:00:08
   ------------ --------------------------- 11.5/36.5 MB 3.5 MB/s eta 0:00:08
   ------------- -------------------------- 12.3/36.5 MB 3.5 MB/s eta 0:00:07
   -------------- ------------------------- 13.1/36.5 MB 3.6 MB/s eta 0:00:07
   --------------- ------------------------ 14.2/36.5 MB 3.6 MB/s eta 0:00:07
   ---------------- ----------------------- 14.9/36.5 MB 3.7 MB/s eta 0:00:06
   ----------------- ---------------------- 16.0/36.5 MB 3.7 MB/s eta 0:00:06
   ------------------ --------------------- 17.0/36.5 MB 3.8 MB/s eta 0:00:06
   ------------------- -------------------- 18.1/36.5 MB 3.8 MB/s eta 0:00:05
   -------------------- ------------------- 19.1/36.5 MB 3.8 MB/s eta 0:00:05
   ---------------------- ----------------- 20.2/36.5 MB 3.9 MB/s eta 0:00:05
   ---------------------- ----------------- 21.0/36.5 MB 3.9 MB/s eta 0:00:05
   ----------------------- ---------------- 21.8/36.5 MB 3.9 MB/s eta 0:00:04
   ------------------------ --------------- 22.5/36.5 MB 3.9 MB/s eta 0:00:04

WARNING: Cache entry deserialization failed, entry ignored
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ragss\.conda\envs\codealpha_ai\Lib\site-packages\~umpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
huggingface-hub 1.18.0 requires click>=8.4.0, but you have click 8.3.0 which is incompatible.

# Step 2 Import Libraries

In [53]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
import re
import string
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
import streamlit as st
from sklearn.metrics.pairwise import cosine_similarity

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ragss\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

# Step 3 Load and Merge Dataset

In [8]:
mental_df  = pd.read_csv(r'D:/Project/codealpha_project/Task2_FAQ_Chatbot/dataset/Mental_Health_FAQ.csv')
medquad_df = pd.read_csv(r'D:/Project/codealpha_project/Task2_FAQ_Chatbot/dataset/medquad.csv')

In [9]:
medquad_df.head()

,question,answer,source,focus_area
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea...",NIHSeniorHealth,Glaucoma
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...,NIHSeniorHealth,Glaucoma
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ...",NIHSeniorHealth,Glaucoma
4,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma

In [10]:
mental_df.head()

,Question_ID,Questions,Answers
0,1590140,What does it mean to have a mental illness?,Mental illnesses are health conditions that di...
1,2110618,Who does mental illness affect?,It is estimated that mental illness affects 1 ...
2,6361820,What causes mental illness?,It is estimated that mental illness affects 1 ...
3,9434130,What are some of the warning signs of mental i...,Symptoms of mental health disorders vary depen...
4,7657263,Can people with mental illness recover?,"When healing from mental illness, early identi..."

In [15]:
medquad_df = medquad_df[['question', 'answer']]
mental_df = mental_df[['Questions', 'Answers']]

# Rename Mental Health columns
mental_df = mental_df.rename(columns={
    'Questions': 'question',
    'Answers': 'answer'
})

# Combine the datasets
df = pd.concat([medquad_df, mental_df], ignore_index=True)

df = df.drop_duplicates(subset='question')

df = df.dropna(subset=['question', 'answer'])

df = df.reset_index(drop=True)

print(f"Total FAQs: {len(df)}")
df.head()

Total FAQs: 15077

,question,answer
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea..."
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ..."
4,Who is at risk for Glaucoma? ?,Anyone can develop glaucoma. Some people are a...

In [16]:
df.to_csv("dataset/final_healthcare_faq.csv", index=False)

In [20]:
df = pd.read_csv('dataset/final_healthcare_faq.csv')
df.head()

,question,answer
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea..."
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ..."
4,Who is at risk for Glaucoma? ?,Anyone can develop glaucoma. Some people are a...

In [21]:
df.columns

Index(['question', 'answer'], dtype='object')

In [29]:
print(df.duplicated().sum())
print(df.duplicated(subset='question').sum())
print(df.duplicated(subset='answer').sum())
print(df.isnull().sum())

0
0
516
question    0
answer      0
dtype: int64

In [30]:
duplicate_answers = df[df.duplicated(subset="answer", keep=False)]
duplicate_answers.head(10)

,question,answer
303,what research (or clinical trials) is being do...,New types of treatment are being tested in cli...
359,what research (or clinical trials) is being do...,New types of treatment are being tested in cli...
377,what research (or clinical trials) is being do...,New types of treatment are being tested in cli...
388,what research (or clinical trials) is being do...,New types of treatment are being tested in cli...
409,what research (or clinical trials) is being do...,New types of treatment are being tested in cli...
418,what research (or clinical trials) is being do...,New types of treatment are being tested in cli...
438,what research (or clinical trials) is being do...,New types of treatment are being tested in cli...
451,what research (or clinical trials) is being do...,New types of treatment are being tested in cli...
459,what research (or clinical trials) is being do...,New types of treatment are being tested in cli...
521,What causes Childhood Brain Stem Glioma ?,The cause of most childhood brain tumors is un...

# Step 4 Preprocess and Vectorize Text

In [32]:
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    tokens = text.split()
    tokens = [word for word in tokens if word not in stop_words]
    return ' '.join(tokens)

In [33]:
df["preprocessed_question"] = df["question"].apply(preprocess_text)
df[["question", "preprocessed_question"]].head()

                                 question preprocessed_question
0                What is (are) Glaucoma ?              glaucoma
1                  What causes Glaucoma ?       causes glaucoma
2     What are the symptoms of Glaucoma ?     symptoms glaucoma
3  What are the treatments for Glaucoma ?   treatments glaucoma
4          Who is at risk for Glaucoma? ?         risk glaucoma

In [43]:
vectorizer = TfidfVectorizer(
    stop_words='english',
    lowercase=True,
    ngram_range=(1, 2)
)

tfidf_matrix = vectorizer.fit_transform(df["preprocessed_question"])

print(f"TF-IDF matrix shape: {tfidf_matrix.shape}")

TF-IDF matrix shape: (15077, 18403)

In [44]:
print(df.head())
print("Vocabulary Size:", len(vectorizer.get_feature_names_out()))

                                 question  \
0                What is (are) Glaucoma ?
1                  What causes Glaucoma ?
2     What are the symptoms of Glaucoma ?
3  What are the treatments for Glaucoma ?
4          Who is at risk for Glaucoma? ?

                                              answer preprocessed_question
0  Glaucoma is a group of diseases that can damag...              glaucoma
1  Nearly 2.7 million people have glaucoma, a lea...       causes glaucoma
2  Symptoms of Glaucoma  Glaucoma can develop in ...     symptoms glaucoma
3  Although open-angle glaucoma cannot be cured, ...   treatments glaucoma
4  Anyone can develop glaucoma. Some people are a...         risk glaucoma
Vocabulary Size: 18403

# Step 5 Preprocess User Query

In [ ]:
def preprocess_query(text):
    processed = preprocess_text(text)
    query_vector = vectorizer.transform([processed])
    return processed, query_vector

processed_query, query_vector = preprocess_query("What are the symptoms of depression?")

print("Processed Query:", processed_query)
print("Query Vector Shape:", query_vector.shape)

Processed Query: symptoms depression
Query Vector Shape: (1, 18403)

# Step 6 Compute Cosine Similarity

In [59]:
similarities = cosine_similarity(query_vector, tfidf_matrix)

best_match_idx = similarities.argmax()

best_score = similarities[0, best_match_idx]

thereshold = 0.30

if best_score >= thereshold:
    print("Best Matching Question:")
    print(df.loc[best_match_idx, "question"])
else:
    print("No relevant answer found.")

Best Matching Question:
What are the symptoms of Depression ?

In [61]:
print("Best Matching Question:", best_match_idx)
print(df.loc[best_match_idx, "question"])

print("\nBest Answer:")
print(df.loc[best_match_idx, "answer"])

print("\nSimilarity Score:", best_score)

Best Matching Question: 142
What are the symptoms of Depression ?

Best Answer:
Common Symptoms There are many symptoms associated with depression, and some will vary depending on the individual. However, some of the most common symptoms are listed below. If you have several of these symptoms for more than two weeks, you may have depression. - feeling nervous or emotionally "empty"  - feelings of excessive guilt or worthlessness  - tiredness or a "slowed down" feeling  - restlessness and irritability  - feeling like life is not worth living  - sleep problems, including trouble getting to sleep, wakefulness in the middle of the night, or sleeping too much  - eating more or less than usual, usually with unplanned weight gain or loss  - having persistent headaches, stomach-aches or other chronic pain that does not go away when treated  - loss of interest in once pleasurable activities, including sex  - frequent crying  - difficulty focusing, remembering or making decisions  - thoughts of death or suicide, or a suicide attempt feeling nervous or emotionally "empty" feelings of excessive guilt or worthlessness tiredness or a "slowed down" feeling restlessness and irritability feeling like life is not worth living sleep problems, including trouble getting to sleep, wakefulness in the middle of the night, or sleeping too much eating more or less than usual, usually with unplanned weight gain or loss having persistent headaches, stomach-aches or other chronic pain that does not go away when treated loss of interest in once pleasurable activities, including sex frequent crying difficulty focusing, remembering or making decisions thoughts of death or suicide, or a suicide attempt Is it Depression or Something Else? The first step to getting appropriate treatment is to visit a doctor. Certain medications taken for other medical conditions, vitamin B12 deficiency, some viruses, or a thyroid disorder can cause symptoms similar to depression. If an older adult is taking several medications for other conditions and is depressed, seeing a doctor is especially important. A doctor can rule out medications or another medical condition as the cause of the depression by doing a complete physical exam, interview, and lab tests. If these other factors can be ruled out, he or she may refer you to a mental health professional, such as a psychologist, counselor, social worker, or psychiatrist. Some doctors called geriatric psychiatrists and clinical geropsychologists are specially trained to treat depression and other mental illnesses in older adults. The doctor or mental health professional will ask about the history of your symptoms, such as when they started, how long they have lasted, their severity, whether they have occurred before, and if so, whether they were treated and how. He or she will then diagnose the depression and work with you to choose the most appropriate treatment.

Similarity Score: 1.0000000000000002

# Step 7 Generate Best Matching Response

In [67]:
def get_response(user_query, thereshold=0.30):
    processed_query = preprocess_text(user_query)
    
    query_vector = vectorizer.transform([processed_query])
    
    similarities = cosine_similarity(query_vector, tfidf_matrix)
    
    best_match_idx = similarities.argmax()
    best_score = similarities[0, best_match_idx]
    
    if best_score >= thereshold:
        return {
            "question": df.loc[best_match_idx, "question"],
            "answer": df.loc[best_match_idx, "answer"],
            "score": best_score
        }
    else:
        return {
            "question": None,
            "answer": "I'm sorry, I couldn't find a relevant answer to your question.",
            "score": best_score
        }

In [83]:
result = get_response("What is stomach disorder?")

print("Matched Question:", result["question"])
print("Answer:", result["answer"])
print("Similarity Score:", result["score"])

Matched Question: What is (are) Stomach Cancer ?
Answer: The stomach is an organ between the esophagus and the small intestine. It mixes food with stomach acid and helps digest protein. Stomach cancer mostly affects older people - two-thirds of people who have it are over age 65. Your risk of getting it is also higher if you       - Have had a Helicobacter pylori infection    - Have had stomach inflammation    - Are a man    - Eat lots of salted, smoked, or pickled foods     - Smoke cigarettes     - Have a family history of stomach cancer       It is hard to diagnose stomach cancer in its early stages. Indigestion and stomach discomfort can be symptoms of early cancer, but other problems can cause the same symptoms. In advanced cases, there may be blood in your stool, vomiting, unexplained weight loss, jaundice, or trouble swallowing. Doctors diagnose stomach cancer with a physical exam, blood and imaging tests, an endoscopy, and a biopsy.    Because it is often found late, it can be hard to treat stomach cancer. Treatment options include surgery, chemotherapy, radiation or a combination.    NIH: National Cancer Institute
Similarity Score: 0.5507562641428011

In [73]:
matches = df[df["question"].str.contains("stomach", case=False, na=False)]
print(matches[["question"]].head(15077))
print("Count:", len(matches))

                                     question
1451        What is (are) Stomach Disorders ?
1529           What is (are) Stomach Cancer ?
6327  What is (are) Familial stomach cancer ?
Count: 3

In [74]:
matches = df[df["question"].str.contains("warning", case=False, na=False)]
print(matches[["question"]])

                                                question
14982  What are some of the warning signs of mental i...

In [75]:
query = "What are some of the warning signs of mental illness?"

processed = preprocess_text(query)
query_vector = vectorizer.transform([processed])

similarities = cosine_similarity(query_vector, tfidf_matrix)

best_idx = similarities.argmax()
best_score = similarities[0, best_idx]

print("Processed:", processed)
print("Best score:", best_score)
print("Best question:", df.iloc[best_idx]["question"])

Processed: warning signs mental illness
Best score: 1.0000000000000002
Best question: What are some of the warning signs of mental illness?

In [76]:
print("=" * 50)
print("User Query:", query)
print("Processed Query:", processed_query)
print("Best Match Index:", best_match_idx)
print("Best Score:", best_score)
print("Matched Question:", df.iloc[best_match_idx]["question"])
print("=" * 50)

==================================================
User Query: What are some of the warning signs of mental illness?
Processed Query: symptoms depression
Best Match Index: 142
Best Score: 1.0000000000000002
Matched Question: What are the symptoms of Depression ?
==================================================